// Story links and exported names for the public component explorer.
export const componentCatalog = [
  {
    name: "Accordion",
    category: "Layout",
    components: ["Accordion"],
    href: "?path=/story/components-accordion--default",
  },
  {
    name: "AppShell",
    category: "Layout",
    components: ["AppShell"],
    href: "?path=/story/components-appshell--overview",
  },
  {
    name: "Button",
    category: "Actions and overlays",
    components: ["Button"],
    href: "?path=/story/components-button--overview",
  },
  {
    name: "ButtonLink",
    category: "Actions and overlays",
    components: ["ButtonLink"],
    href: "?path=/story/components-buttonlink--overview",
  },
  {
    name: "Checkbox",
    category: "Forms",
    components: ["Checkbox"],
    href: "?path=/story/components-checkbox--default",
  },
  {
    name: "Chip",
    category: "Display and feedback",
    components: ["Chip"],
    href: "?path=/story/components-chip--overview",
  },
  {
    name: "ChoiceButton",
    category: "Actions and overlays",
    components: ["ChoiceButton"],
    href: "?path=/story/components-choicebutton--overview",
  },
  {
    name: "CodeBlock",
    category: "Display and feedback",
    components: ["CodeBlock"],
    href: "?path=/story/components-codeblock--default",
  },
  {
    name: "CodeText",
    category: "Display and feedback",
    components: ["CodeText"],
    href: "?path=/story/components-codetext--overview",
  },
  {
    name: "CollectionEditor",
    category: "Forms",
    components: ["CollectionEditor"],
    href: "?path=/story/components-collectioneditor--overview",
  },
  {
    name: "Combobox",
    category: "Forms",
    components: ["Combobox"],
    href: "?path=/story/components-combobox--overview",
  },
  {
    name: "ContextMenu",
    category: "Actions and overlays",
    components: ["ContextMenu"],
    href: "?path=/story/components-contextmenu--overview",
  },
  {
    name: "DataTable",
    category: "Display and feedback",
    components: [
      "DataTable",
      "DataTableHeadCell",
      "DataTableCell",
      "DataTableStateRow",
    ],
    href: "?path=/story/components-datatable--overview",
  },
  {
    name: "DescriptionList",
    category: "Display and feedback",
    components: ["DescriptionList"],
    href: "?path=/story/components-descriptionlist--overview",
  },
  {
    name: "Dialog",
    category: "Actions and overlays",
    components: ["Dialog"],
    href: "?path=/story/components-dialog--overview",
  },
  {
    name: "Disclosure",
    category: "Layout",
    components: ["Disclosure"],
    href: "?path=/story/components-disclosure--default",
  },
  {
    name: "Drawer",
    category: "Actions and overlays",
    components: ["Drawer"],
    href: "?path=/story/components-drawer--overview",
  },
  {
    name: "Editor layout",
    category: "Layout",
    components: ["PageHeader", "Card", "FormRow", "FormActions", "FilterBar"],
    href: "?path=/story/components-editor-layout--overview",
  },
  {
    name: "EmptyState",
    category: "Display and feedback",
    components: ["EmptyState"],
    href: "?path=/story/components-emptystate--overview",
  },
  {
    name: "EntityPicker",
    category: "Forms",
    components: ["EntityPicker"],
    href: "?path=/story/components-entitypicker--overview",
  },
  {
    name: "FileDropzone",
    category: "Forms",
    components: ["FileDropzone"],
    href: "?path=/story/components-filedropzone--overview",
  },
  {
    name: "IconButton",
    category: "Actions and overlays",
    components: ["IconButton"],
    href: "?path=/story/components-iconbutton--overview",
  },
  {
    name: "ImagePreview",
    category: "Display and feedback",
    components: ["ImagePreview"],
    href: "?path=/story/components-imagepreview--overview",
  },
  {
    name: "Inline",
    category: "Layout",
    components: ["Inline"],
    href: "?path=/story/components-inline--overview",
  },
  {
    name: "Listbox",
    category: "Forms",
    components: ["Listbox"],
    href: "?path=/story/components-listbox--overview",
  },
  {
    name: "LoadingState",
    category: "Display and feedback",
    components: ["LoadingState"],
    href: "?path=/story/components-loadingstate--overview",
  },
  {
    name: "LocalizedField",
    category: "Forms",
    components: ["LocalizedField"],
    href: "?path=/story/components-localizedfield--overview",
  },
  {
    name: "MarkdownContent",
    category: "Display and feedback",
    components: ["MarkdownContent"],
    href: "?path=/story/components-markdowncontent--overview",
  },
  {
    name: "Menu",
    category: "Actions and overlays",
    components: ["Menu"],
    href: "?path=/story/components-menu--default",
  },
  {
    name: "Messages",
    category: "Display and feedback",
    components: ["MessagesProvider"],
    href: "?path=/story/components-messages--overview",
  },
  {
    name: "Navigation",
    category: "Navigation",
    components: [
      "Navigation",
      "NavigationLink",
      "NavigationAction",
      "NavigationGroup",
    ],
    href: "?path=/story/components-navigation--overview",
  },
  {
    name: "Notice",
    category: "Display and feedback",
    components: ["Alert", "Notice"],
    href: "?path=/story/components-notice--default",
  },
  {
    name: "NumberField",
    category: "Forms",
    components: ["NumberField"],
    href: "?path=/story/components-numberfield--overview",
  },
  {
    name: "Page layout",
    category: "Layout",
    components: ["PageContainer", "Grid", "LinkCard"],
    href: "?path=/story/components-page-layout--overview",
  },
  {
    name: "Pagination",
    category: "Navigation",
    components: ["Pagination"],
    href: "?path=/story/components-pagination--overview",
  },
  {
    name: "Popover",
    category: "Actions and overlays",
    components: ["Popover"],
    href: "?path=/story/components-popover--default",
  },
  {
    name: "Progress",
    category: "Display and feedback",
    components: ["Progress"],
    href: "?path=/story/components-progress--overview",
  },
  {
    name: "ResizablePanels",
    category: "Layout",
    components: ["ResizablePanels"],
    href: "?path=/story/components-resizablepanels--overview",
  },
  {
    name: "ScrollArea",
    category: "Layout",
    components: ["ScrollArea"],
    href: "?path=/story/components-scrollarea--follow-latest",
  },
  {
    name: "Select",
    category: "Forms",
    components: ["Select"],
    href: "?path=/story/components-select--overview",
  },
  {
    name: "Stack",
    category: "Layout",
    components: ["Stack"],
    href: "?path=/story/components-stack--overview",
  },
  {
    name: "Stat",
    category: "Display and feedback",
    components: ["Stat", "ChartFrame"],
    href: "?path=/story/components-stat--overview",
  },
  {
    name: "StatusBadge",
    category: "Display and feedback",
    components: ["StatusBadge"],
    href: "?path=/story/components-statusbadge--default",
  },
  {
    name: "Tabs",
    category: "Navigation",
    components: ["Tabs"],
    href: "?path=/story/components-tabs--default",
  },
  {
    name: "TextField",
    category: "Forms",
    components: ["TextField"],
    href: "?path=/story/components-textfield--default",
  },
  {
    name: "TextInput",
    category: "Forms",
    components: ["TextInput"],
    href: "?path=/story/components-textinput--overview",
  },
  {
    name: "Textarea",
    category: "Forms",
    components: ["Textarea"],
    href: "?path=/story/components-textarea--overview",
  },
  {
    name: "TextareaComposer",
    category: "Forms",
    components: ["TextareaComposer"],
    href: "?path=/story/components-textareacomposer--overview",
  },
  {
    name: "Theme",
    category: "Display and feedback",
    components: ["Theme"],
    href: "?path=/story/components-theme--overview",
  },
  {
    name: "Toast",
    category: "Display and feedback",
    components: ["ToastProvider"],
    href: "?path=/story/components-toast--overview",
  },
  {
    name: "Toolbar",
    category: "Actions and overlays",
    components: ["Toolbar", "ToggleButton"],
    href: "?path=/story/components-toolbar--overview",
  },
  {
    name: "Tooltip",
    category: "Actions and overlays",
    components: ["Tooltip"],
    href: "?path=/story/components-tooltip--default",
  },
  {
    name: "TreeView",
    category: "Navigation",
    components: ["TreeView"],
    href: "?path=/story/components-treeview--overview",
  },
  {
    name: "UsageMeter",
    category: "Display and feedback",
    components: ["UsageMeter"],
    href: "?path=/story/components-usagemeter--default",
  },
] as const;
